name: publish

on:
  push:
    branches: [ "zero" ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "zero" ]

env:
  REGISTRY: ghcr.io
  USER: ${{ github.actor }}
  PASS: ${{ secrets.GITHUB_TOKEN }}
  IMAGE_NAME: ${{ github.repository }}
  TAG: latest

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.USER }}
          password: ${{ env.PASS }} 
      - name: Build and publish
        run: |
          make IMAGE_NAME=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }} TAG=${{ env.TAG }} build
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}
